import Head from "next/head";
import Layout from "@/components/Layout";
import Contents from "@/components/contents/Contents";
import useMoveScroll from "@/hooks/useMoveScroll";

export default function Home() {
  const moveTable = {
    about: useMoveScroll(),
    skills: useMoveScroll(),
    archiving: useMoveScroll(),
    projects: useMoveScroll(),
    education: useMoveScroll(),
    career: useMoveScroll(),
    length: 5,
  };

  return (
    <Layout moveTable={moveTable}>
      <Head>
        <title>nno3onn&#39;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700;900&display=swap" rel="stylesheet" />
      </Head>
      <Contents moveTable={moveTable} />
    </Layout>
  );
}
